apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {}

    http {
      upstream app_upstream {
        server app1:3000 weight=1;
        server app2:3002 weight=1;
       
      }

      server {
        listen 8080;


        allow 10.11.16.147/32;
        allow 172.31.98.137/32;
     
        deny all;

        
        location / {
          proxy_pass http://app_upstream;
        }
      }
    }
