events {}

http {
  upstream app_upstream {
    server app1:3000 weight=1;
    server app2:3002 weight=1;
    # you can also add basic failure handling:
    # server app1:3000 weight=1 max_fails=3 fail_timeout=10s;
    # server app2:3001 weight=1 max_fails=3 fail_timeout=10s;
  }

  server {
    listen 80;


    allow 10.11.16.147/32;
    allow 172.31.98.137/32;
 
    deny all;

    # All traffic split 50/50 between app1 & app2
    location / {
      proxy_pass http://app_upstream;
    }
  }
}
